### PR TITLE
Implement outline support

### PR DESCRIPTION
**Pull request by 0rvar**
This pull requests implements outline support for the document outlines [introduced in Visual Studio Code 1.25](https://code.visualstudio.com/updates/v1_25#_document-symbols).

* Add and register a SymbolProvider based on `flow ast`
* Rewrite `astToOutline` to work with modern flow AST
* Change `astToOutline` interface in `FlowService`
* Completely remove *nuclide-tokenized-text* to avoid having to upgrade
  tokenization to new AST - no code in this project needs the tokens.

There is already Outline support built into the *TypeScript and JavaScript Language Features* plugin, but many disable this plugin to reduce the amount of noise in autocomplete.

Comparison between the built in TypeScript outline provider and this outline provider:
screen shot 2018-07-16 at 12 40 52

### CODE REVIEW

**Comment by thymikee** [comment]
Awesome work! FYI: for LSP users (`flow.useLSP` option) this is already working :)

**Comment by 0rvar** [comment]
Oh, damn. `flow.useLSP` works well. This patch is not needed in that case.

**Comment by orta** [comment]
Yeah, I'd love to get that stable enough to wipe all the non-LSP code in this project. 

@0rvar if you're happy with the LSP version (give it a few days) then we can close this PR (not much point introducing extra changes) 👍

**Comment by 0rvar** [comment]
Sounds good to me!

**Pull request closed without merging**
