### PR TITLE
Support running flow on all files

### PR DESCRIPTION
**Pull request by doshisid**
Solves #141

### CODE REVIEW

**Comment by orta** [comment]
This looks 👍 to me

**Comment by orta** [comment]
@gabelevi as there's not been too many incoming PRs ATM, might be worth shipping this as a point release

**Comment by gabelevi** [comment]
Sure, I can do that.

**Comment by gabelevi** [comment]
Ok, 0.7.1 is published!

**Comment by orta** [comment]
Awesome - thanks

**Pull request merged**
