### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by Mayank1791989**
- [feat] Update bundled flow-bin v0.103.0
- [fix] closes issue #350 
- [fix] fix debug task

### CODE REVIEW

**Comment by orta** [comment]
any idea what's up with CLA bot?

**Comment by Mayank1791989** [comment]
No idea. Maybe because of tags I pushed. But I don't know why github not showing v1.1.2, v1.1.3 & v1.1.4 tags.

**Comment by orta** [comment]
:D

**Comment by orta** [comment]
```
Publishing flowtype.flow-for-vscode@1.2.0...
 DONE  Published flowtype.flow-for-vscode@1.2.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode (might take a few seconds for it to show up).
```

**Comment by Mayank1791989** [comment]
@orta Also tag the release

**Comment by orta** [comment]
```
orta@Perl ~/d/v/flow-for-vscode> git tag 1.2.0
orta@Perl ~/d/v/flow-for-vscode> git push --tags
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/flowtype/flow-for-vscode.git
 * [new tag]         1.2.0 -> 1.2.0
```

👍

**Pull request merged**
