### PR TITLE
Status indicator

### PR DESCRIPTION
**Pull request by Gozala**
Implements status indicator as per #40

### CODE REVIEW

**Comment by orta** [comment]
Any chance we can get a screenshot?

**Comment by orta** [comment]
Other than that - everything looks 👍

**Comment by Gozala** [comment]
> Any chance we can get a screenshot?

status indicator

**Comment by orta** [comment]
Alright, that looks good - one little addition, and this is good to go. This extension has an output channel, can you make clicking on the status toggle the visibility for it?  Then people know where this output is coming from.

**Comment by Gozala** [comment]
@orta latest change shows the output when indicator is clicked. It does not toggle though because from what I can tell there is no way of telling if the output channel is shown or not. Note that I can't just track that state on my own as there's no way of telling if initial state is shown or hidden. If you really want toggling I can go under assumption it's hidden initially, but in that case if output happened to be open, first click will do nothing.

P.S.: It also seems that showing output channel does not always work, not sure why.

**Comment by orta** [comment]
interesting, I think just showing is reasonable. The worrying thing is the unreliablilty - perhaps it's worth adding "Flow: " beforehand then so that people know what it going on? 

My guess is that the spinner might be re-creating the status bar item, and potentially the re-hooking of the click notifier happens a tick or two after, but the setInterval will reset it again before it's been added back?

**Comment by Gozala** [comment]
> interesting, I think just showing is reasonable. The worrying thing is the unreliablilty - perhaps it's worth adding "Flow: " beforehand then so that people know what it going on?

If you hover the status indicator tooltip will appear with a message: `'Flow is type checking'`, which I assumed was enough & realistically user might wonder what's that only first time around. That being said if you really want to I can add additional setting to allow prefxing spinner with arbitrary string with a default `"Flow: "`.  

> My guess is that the spinner might be re-creating the status bar item, and potentially the re-hooking of the click notifier happens a tick or two after, but the setInterval will reset it again before it's been added back?

Well the code I've written [just updates `text` and visibility](https://github.com/flowtype/flow-for-vscode/pull/85/files#diff-bc022fab4f0d6d7da9fc4f0a72b93a81R60) of the same statusbar item. That being said I don't know what vscode does under the hood, it could be that updating text does some of the rehooking as you described but find it hard to believe. Also I tried spinner that does not update text nor visibility & it did not seem to make any difference :(

**Comment by orta** [comment]
Alright, that seems 👍 with me ( I had the same issues after https://github.com/orta/vscode-jest/pull/63 was merged on another project - but haven't really found an answer )

The hover alt text should be fine. Let's do it.

**Pull request merged**
