### PR TITLE
Add flow coverage support

### PR DESCRIPTION
**Pull request by thymikee**
**Summary**

Flow coverage support. 

StatusBar (clicking toggles uncovered code mode):

screen shot 2017-04-09 at 03 29 35

Uncovered code mode:

screen shot 2017-04-09 at 03 29 48

screen shot 2017-04-09 at 03 31 58

### CODE REVIEW

**Comment by orta** [comment]
Yeah, great - this looks good to me 👍 

Very cool

**Comment by jacobk** [comment]
Is it possible to disable this feature?

I've experience a big degradation in performance of vscode latley and I've tried to disable most other plugins but cannot find the root cause.

This seems like it could impact performance and I've had performance issues when trying to use flow coverage in the past too.

@thymikee  Have you noticed anything similar?

**Comment by thymikee** [comment]
Coverage report is run for every diagnostic change, and by default the extension sets:
```
"flow.runOnEdit": true
```
which tells Flow to get diagnostics (coverage included) on every keystroke.
You can set it to false and see if that makes the difference.

Maybe we could defer it somehow, I'll see what can be done if I have some time to work on it.

**Comment by moberemk** [comment]
I'm also running into some weirdness with this where I'm getting "uncovered code" on files that don't even Javascript, like bash scripts.

**Comment by thymikee** [comment]
@jacobk @moberemk I've addressed couple of perf issues in #126

**Comment by moberemk** [comment]
My issue isn't a perf issue though, my issue is that the coverage check is
being applied to the wrong types of files...

**Comment by thymikee** [comment]
That's fixed too.

**Pull request merged**
