### PR TITLE
Update flow-bin lib - 0.93.0 to 0.98.1

### PR DESCRIPTION
**Pull request by leandrobudau**

### CODE REVIEW

**Comment by orta** [comment]
any ideas what's going on with yarn here?

**Comment by Mayank1791989** [comment]
Also update version in .flowconfig that will fix the ci error.

**Comment by Mayank1791989** [comment]
@orta I think @leandrobudau have manually updated the version in yarn.lock file rather than running yarn that is why yarn is failing.

**Comment by leandrobudau** [comment]
Sorry, guys. I tried, but I can't pass on test ci. What I should to do?

**Pull request closed without merging**
