### PR TITLE
Prepare for v0.6.0 release - @gabelevi

### PR DESCRIPTION
**Pull request by orta**
The CHANGELOG entry in #89 shows what has changed, I've given it a run through locally and everything seems to be in order 👍

### CODE REVIEW

**Comment by gabelevi** [comment]
Sweet! Somewhat predictably, I'm traveling so I don't have my Windows laptop on which to test, but happy to publish if you and @Gozala are ready to roll!

**Comment by orta** [comment]
Hah, as always. 

I don't think there was anything that felt like it may be platform specific - however, I guess the problem with those is that you tend not to generally feel it. I'd be fine with going without that test. We'll get issues raised pretty quickly if it did break something.

**Comment by Gozala** [comment]
I do observe some odd behavior when type checking as you type feature - it seems like checks get queued, rather then being cancelled on further edits. So at times I noticed some outdated reports. I would suggest hold off putting out 0.6 so I can look into this and include a fix with next release.

**Comment by gabelevi** [comment]
It looks like flowtype.org/try just [registers checkContents as codemirror's linter function](https://github.com/facebook/flow/blob/cd892906293679dfacd586574246a9d9fbaccfe0/website/_assets/js/tryFlow.js.es6#L276). Not sure how codemirror decides when to call the linter, or whether it decides to cancel the lint when it notices things changing.

**Comment by Gozala** [comment]
Ok it seems that fixing this isn't going to be easy 😢 Problem is vscode is mostly build around the notion of disposables tasks that can be disposed / killed when their work becomes obsolete. But then `FlowServer` and underlying nuclide libraries don't really provide appropriate APIs from what I can tell. Specifically once `FlowService.flowFindDiagnostics`  is invoked, there's no way to abort that taks, at best one can do is just ignore results if results are obsolete. But even then there are two complications:

1. We needs to keep track of running tasks. Specifically we need to keep track of files & their revisions task was scheduled.
2. Once task completes we need to check if report is for the latest revision and if it is only then we want to actually update diagnostics.

It also seems that vscode suggests to use of [language server](https://code.visualstudio.com/docs/extensions/example-language-server) for this kind of tasks and that does seem more appropriate as far as I can tell.
 
files and versions of them that task is running for

**Comment by Gozala** [comment]
I have drafted fix in #92 still need to use it for a bit to see if it actually makes thing better.

**Comment by orta** [comment]
Alright, this is rebased with master - and has #92 #102 inside also. Think we should be good to go.

**Comment by gabelevi** [comment]
Ok, I'll get it published!

**Comment by gabelevi** [comment]
Ok, it's published! https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode

I also pushed a tag. Up to you if you want to merge this PR or whatever.

**Comment by orta** [comment]
Yeah - it's useful for the CHANGELOG entry

**Comment by orta** [comment]
Thanks @gabelevi

**Pull request merged**
