### PR TITLE
Ensure absolute file paths for diagnostics

### PR DESCRIPTION
**Pull request by ryanashcraft**
I've been experiencing an issue with flow-for-vscode's diagnostics where I'm receiving errors like this when clicking on an error in the "problems" view:

screen shot 2017-02-04 at 11 18 28 am

I've dug into this a bit, and it seems the issue is related to a bad assumption that `flow status --json` always returns absolute paths. I'm guessing that most flow projects, the paths are absolute. This is the case with flow-for-vscode. However, with my project, the paths are relative to the project root – without a leading `./`. This causes a problem when the file is converted into a URI with `vscode.Uri.file`, which expects absolute paths and results in an invalid URI.

This change ensures that the file path is always absolute, leveraging the `flowRoot` value from `flowFindDiagnostics`, before converting it into a URI with `vscode.Uri.file`.

---

For additional context, I'm pretty confident I know what is driving this inconsistency with the output of `flow status`. My project is configured to treat our top-level `src` directory to be treated as a module root using `module.system.node.resolve_dirname=src`. We do this so that we can import our own modules similarly to how we import modules from `node_modules`. For example, importing `components/AddToDashboardSelect/AddToDashboardSelect` resolves to `<PROJECT_ROOT>/src/components/AddToDashboardSelect/AddToDashboardSelect`.

Sample output from `./node_modules/.bin/flow status --json` for my project:
```json
{
  "context": "                optionGroups={this.getOptionGroups()}",
  "descr": "tuple type",
  "type": "Blame",
  "loc": {
    "source": "src/components/AddLegendSeriesSelect/AddLegendSeriesSelect.jsx",
    "type": "SourceFile",
    "start": {
      "line": 62,
      "column": 31,
      "offset": 1694
    },
    "end": {
      "line": 62,
      "column": 52,
      "offset": 1716
    }
  },
  "path": "src/components/AddLegendSeriesSelect/AddLegendSeriesSelect.jsx",
  "line": 62,
  "endline": 62,
  "start": 31,
  "end": 52
},
```

Compared to flow-for-vscode:

```json
{
  "context": "\t\tconst line = position.line;",
  "descr": "property `line`",
  "type": "Blame",
  "loc": {
    "source": "/Users/ryanashcraft/Desktop/flow-for-vscode/lib/flowCompletion.js",
    "type": "SourceFile",
    "start": {
      "line": 31,
      "column": 25,
      "offset": 720
    },
    "end": {
      "line": 31,
      "column": 28,
      "offset": 724
    }
  },
  "path": "/Users/ryanashcraft/Desktop/flow-for-vscode/lib/flowCompletion.js",
  "line": 31,
  "endline": 31,
  "start": 25,
  "end": 28
},
```

### CODE REVIEW

**Comment by orta** [comment]
Looks pretty :+1: to me - can you please add a CHANGELOG entry too

**Comment by ryanashcraft** [comment]
@orta updated CHANGELOG

**Comment by orta** [comment]
👍

**Comment by ryanashcraft** [comment]
Thanks @orta!

**Comment by orta** [comment]
Thanks to you for contributing @ryanashcraft

**Pull request merged**
