### PR TITLE
Make addon work on Windows

### LINKED ISSUE #21: Windows support
Flow [now supported on Windows](https://flowtype.org/blog/2016/08/01/Windows-Support.html).
But flow-for-vscode seems not working. **vscode presents no errors** in incorrect code.
I have .flowconfig and //@flow comments.
*flow check* command works and finds errors.

### PR DESCRIPTION
**Pull request by rmevans9**
Note: I was unable to test on other platforms so there should be some level of testing these changes.

Fixes #21

### CODE REVIEW

**Comment by gabelevi** [comment]
Woo! Thanks for fixing this up! I'll test this out on Monday and get it merged!

**Comment by rmevans9** [comment]
Thanks @gabelevi! Looking forward to being able to use Flow in VSCode (without having to run it in dev mode! haha)

**Comment by mike-morrison** [comment]
Just cloned this PR and used it self host style from the main README used a junction point instead of symlink.  Worked great!  I'm on Windows 10 Anniversary Edition.  I did notice some errors during the startup in the vscode developer tools.  They might be expected though.  They don't cause any noticeable issue in the user experience.  Just providing feedback.  Loving it so far!  Thanks.

**Comment by rmevans9** [comment]
@mike-morrison what errors were they?

**Comment by mike-morrison** [comment]
@rmevans9 this is in a working state, btw.  It seems to happen after an indeterminate amount of time, because when I refresh the window it doesn't come back right away.  Self hosted.  It was really my first time playing with Flow.  Awesome technology!

image

**Comment by rmevans9** [comment]
Hmm that's interesting - Cross Spawn is supposed to be fixing the ENOENT errors. What do you get if you run "which" in a command line? does it work?

**Comment by kumarharsh** [comment]
I keep getting this in the developer console:

```
[Extension Host] [2016-08-18T14:26:06.664Z] [ERROR] nuclide -
Invalid JSON result from flow status --json c:\Workspace\...\app.js. JSON: ''.
```

**Comment by mike-morrison** [comment]
@rmevans9 which does not work, not found in cmd and powershell..

**Comment by rmevans9** [comment]
@mike-morrison try "npm i -g which" and then see if that fixes your error

**Comment by kumarharsh** [comment]
I have git for windows installed, and add the directory with the binaries to my path, which has `which`.

**Comment by mike-morrison** [comment]
@rmevans error is gone after installing which globally.

**Comment by mike-morrison** [comment]
@rmevans9 I also removed "which" from npm and added the C:\Git\usr\bin to my path, which also resolved it.

**Comment by rmevans9** [comment]
Excellent. @gabelevi have you had a chance to take a look at this?

**Comment by gabelevi** [comment]
Sorry for the delay! It seems like master is somewhat broken. I'm surprised this PR worked for you in the first place! At the very least, the package.json is missing `lru-cache` as a dependency.

I have a massive PR that I'll put up shortly. It fixes all the flow errors as of Flow v0.31.0, adds the missing npm dependency, and bumps the vscode engine version to 1.4. The vscode extension seems to work on top of that.

After rebasing this PR on top of that, this seems to work. So I'll merge this PR immediately. Then I'll get master cleaned up and this extension published.

Sorry for the delay!

**Comment by gabelevi** [comment]
https://github.com/flowtype/flow-for-vscode/pull/28 is the PR to fix master. Once that is merged, I'll need to publish a new version of the extension.

I suppose I need to figure out who owns the "flowtype" publisher, so I can publish. @bpasero, @nmote or @Arilas - do any of you have access?

**Comment by kumarharsh** [comment]
@gabelevi it seems like this feature is not published yet...

**Comment by rickmed** [comment]
has this been released yet?

**Pull request merged**
