### PR TITLE
Do not report obsolete diagnostics.

### PR DESCRIPTION
**Pull request by Gozala**
With this change extension tracks requested diagnostics, so that obsolete reports can be ignored. I don't know yet to what degree this fixes issues reported in https://github.com/flowtype/flow-for-vscode/pull/91#issuecomment-287220095 but I thought I'd send the pull to give an idea where I'm heading with this.

### CODE REVIEW

**Comment by orta** [comment]
All of this looks good for a conceptual side, it's hard to grok the whole subscriptions business. I don't actively work in any flow codebases, so I can't give this a longer test run. Will be happy to give you some time to make an opinion on it's long term 👍-ness

**Comment by orta** [comment]
@Gozala got an opinion?

**Comment by Gozala** [comment]
@orta I apologize for taking this long to get back to this. Here are my thoughts:

1. I think this improves things a lot. In particular, outdated errors are no longer reported. 
1. I think there is a need for a better long term solution, as this just keeps spinning flow process over & over, as there is no way to cancel the check from what I can tell. It also seems that now there is a [`flow ide`](https://github.com/facebook/flow/releases/tag/v0.42.0) command which I suspect could address exactly that concern.
1. As I mentioned [in my comment on #84](https://github.com/flowtype/flow-for-vscode/issues/84#issuecomment-286917313) I think flow should really reconsider hard requirement of `.flowconfig` in favor of providing a project root directory.

**Comment by orta** [comment]
No worries, you should never feel guilty for your OSS contributions.

OK - so it looks like I pulled off a bad rebase in the GitHub UI. :) (on that subject.) I'm happy to merge this once green.

1) 👍 
2) Agreed on `flow ide` - ( re: https://github.com/flowtype/flow-for-vscode/issues/36 )
3) I'd love to see that, but those changes would need to appear in flow first before this extension can react to it, really.

**Pull request closed without merging**
