### PR TITLE
Added useNPMPackagedFlow to README.md

### PR DESCRIPTION
**Pull request by agrcrobles**
Updated README.md as discussed in #64

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this looks good to me.

**Comment by Download** [comment]
I wish i would specify *where* to put these configuration options. In VS code settings? Workspace settings? Or in .flowconfig?

First thing the readme does is tell you to change some settings, without saying where... then you are left wondering 'how hard will this be? should I try something else?'

**Comment by agrcrobles** [comment]
@Download You can add it in `settings.json` go to File -> Preferences -> User Settings

**Comment by Download** [comment]
Thanks!

How can I tell if it's working? I restarted VS studio code and the green curly lines and the tooltip saying the settings are not recognized have disappeared. So that looks good. But other than that I see no effects? Should auto suggest work now?

**Pull request merged**
